train:
  seed: 42
  max_iter: 200_000
  batch_size: 24
  log_freq: 50
  val_freq: 500
  save_freq: 5000
  max_grad_norm: 100.
  valid_max_batch: 32
  optimizer:
    type: adam
    lr: 3.e-4
    weight_decay: 0.
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.5
    patience: 10
    min_lr: 1.e-4

datasets:
  type: ns
  root: data/
  train:
    data_file: ns_nw100_nf100_s64_t50_mu0.001.h5
  test:
    data_file: ns_nw10_nf100_s64_t50_mu0.001.h5

model:
  kernel: randn
encoder:
  type: fno_cond
  n_modes: [ 16, 16, 16 ]
  emb_channels: 16
  hidden_channels: 32
  proj_channels: 256
  n_layers: 2
cond_type: ic

n_sample: 2
n_eval: 1
sample_dims: [ 64, 64, 50 ]
vis:
  vmin: -2.5
  vmax: 2.5
